services:

  db:
    image: postgres:16
    container_name: hammer_systems_db
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: hammer_systems_redis
    expose:
      - 6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

  project:
    build:
      context: .
    container_name: hammer_systems_project
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static:/project/static/
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    image: nginx
    container_name: hammer_systems_nginx
    ports:
      - "80:80"
    volumes:
      - static:/var/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project

volumes:
  db_data:
  redis_data:
  static:

