# Generated by Django 5.2.4 on 2025-07-25 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='Код')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activated_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активированный код',
                'verbose_name_plural': 'Активированные коды',
            },
        ),
    ]
